#define CONNECT     "connect"
#define DIR         "dir"
#define MOVE        "move"
#define CREATE      "create"
#define RENAME      "rename"
#define DOWNLOAD    "download"
#define UPLOAD      "upload"
#define DEL         "del"
#define CLEAR       "clear"
#define EXIT        "exit"
#define HELP        "help"

#define USER        "123"
#define PASS        "123"
